export const affirmations = [
  { affirmation: "I am enough." },
  { affirmation: "I accept myself unconditionally." },
  { affirmation: "I love and respect myself." },
  { affirmation: "I am worthy of love and happiness." },
  { affirmation: "I embrace my flaws and imperfections." },
  { affirmation: "I am confident in my abilities." },
  { affirmation: "I deserve to be treated with kindness and respect." },
  { affirmation: "I forgive myself for past mistakes." },
  { affirmation: "I am proud of who I am becoming." },
  { affirmation: "I trust myself to make the right decisions." },
  { affirmation: "I am comfortable being myself." },
  { affirmation: "I am deserving of success and happiness." },
  { affirmation: "I am worthy of all the good things life has to offer." },
  { affirmation: "I believe in myself and my abilities." },
  { affirmation: "I am confident in my ability to achieve my goals." },
  { affirmation: "I am valuable and deserving of love." },
  { affirmation: "I am capable of overcoming any challenge." },
  { affirmation: "I am in control of my thoughts and emotions." },
  { affirmation: "I radiate positivity and attract good things into my life." },
  { affirmation: "I am deserving of respect and admiration." },
  {
    affirmation:
      "I am strong, resilient, and capable of handling whatever comes my way.",
  },
  { affirmation: "I am worthy of success, prosperity, and abundance." },
  { affirmation: "I am deserving of love and affection." },
  { affirmation: "I am worthy of forgiveness and second chances." },
  { affirmation: "I am enough just as I am." },
  { affirmation: "I am deserving of happiness and fulfillment." },
  { affirmation: "I trust myself to make the right decisions for myself." },
  { affirmation: "I am worthy of all the good things life has to offer." },
  { affirmation: "I am confident in my ability to create a life I love." },
  { affirmation: "I am worthy of respect and admiration." },
  { affirmation: "I am deserving of love, happiness, and success." },
  { affirmation: "I am proud of who I am and how far I've come." },
  { affirmation: "I am worthy of love and affection." },
  { affirmation: "I am deserving of all the good things that come my way." },
  { affirmation: "I am capable of achieving my dreams." },
  { affirmation: "I am enough just as I am." },
  { affirmation: "I trust myself to make the best decisions for myself." },
  { affirmation: "I am confident in my abilities to succeed." },
  { affirmation: "I am worthy of all the good things life has to offer." },
  { affirmation: "I am deserving of love, happiness, and success." },
  { affirmation: "I am enough just as I am." },
  { affirmation: "I am confident in my ability to achieve my goals." },
  { affirmation: "I am deserving of respect and admiration." },
  { affirmation: "I am capable of overcoming any challenge." },
  { affirmation: "I am in control of my thoughts and emotions." },
  {
    affirmation:
      "I am radiating positivity and attracting good things into my life.",
  },
  { affirmation: "I am worthy of success, prosperity, and abundance." },
  { affirmation: "I am deserving of love and affection." },
  { affirmation: "I am worthy of forgiveness and second chances." },
  { affirmation: "I am enough just as I am." },
  { affirmation: "I am deserving of happiness and fulfillment." },
  { affirmation: "I am confident in my ability to create a life I love." },
  { affirmation: "I am worthy of respect and admiration." },
  { affirmation: "I am deserving of love, happiness, and success." },
  { affirmation: "I am proud of who I am and how far I've come." },
  { affirmation: "I am worthy of love and affection." },
  { affirmation: "I am deserving of all the good things that come my way." },
  { affirmation: "I am capable of achieving my dreams." },
  { affirmation: "I am enough just as I am." },
  { affirmation: "I trust myself to make the best decisions for myself." },
  { affirmation: "I am confident in my abilities to succeed." },
  { affirmation: "I am worthy of all the good things life has to offer." },
  { affirmation: "I am deserving of love, happiness, and success." },
  { affirmation: "I am enough just as I am." },
  { affirmation: "I am confident in my ability to achieve my goals." },
  { affirmation: "I am deserving of respect and admiration." },
  { affirmation: "I am capable of overcoming any challenge." },
  { affirmation: "I am in control of my thoughts and emotions." },
  {
    affirmation:
      "I am radiating positivity and attracting good things into my life.",
  },
  { affirmation: "I am worthy of success, prosperity, and abundance." },
  { affirmation: "I am deserving of love and affection." },
];
